import type { EPQRQuestion } from '../../types/epqr.types';

const questions: EPQRQuestion[] = [
    { "id": 1, "text": "¿le gusta abundancia de excitación y bullicio a su alrededor?", "scale": "E", "positive": true },
    { "id": 2, "text": "¿tiene a menudo un sentimiento de intranquilidad, como si quisiera algo, pero sin saber que?", "scale": "N", "positive": true },
    { "id": 3, "text": "¿tiene casi siempre una contestación lista ala mano cuando se le habla?", "scale": "E", "positive": true },
    // { "id": 4, "text": "¿se siente algunas veces feliz, algunas veces triste, sin una razón real?", "scale": "N", "positive": true },
    // { "id": 5, "text": "¿permanece usualmente retraído (a) en fiestas y reuniones?", "scale": "E", "positive": false },
    // { "id": 6, "text": "cuando era niño(a) ¿hacia siempre inmediatamente lo que le decían, sin refunfuñar?", "scale": "L", "positive": true },
    // { "id": 7, "text": "¿se enfada o molesta a menudo?", "scale": "N", "positive": true },
    // { "id": 8, "text": "cuando lo(a) meten a una pelea ¿prefiere sacar los trapitos al aire de una vez por todas, en vez de quedar callado(a) esperando que las cosas se calmen solas?", "scale": "E", "positive": true },
    // { "id": 9, "text": "¿es usted triste, melancólico (a)?", "scale": "N", "positive": true },
    // { "id": 10, "text": "¿le gusta mezclarse con la gente?", "scale": "E", "positive": true },
    // { "id": 11, "text": "¿a perdido a menudo el sueño por sus preocupaciones?", "scale": "N", "positive": true },
    // { "id": 12, "text": "¿se pone a veces malhumorado (a)?", "scale": "L", "positive": false },
    // { "id": 13, "text": "¿se catalogaría a si mismo(a) como despreocupado (a) o confiado a su buena suerte?", "scale": "E", "positive": true },
    // { "id": 14, "text": "¿se decide a menudo demasiado tarde?", "scale": "N", "positive": true },
    // { "id": 15, "text": "¿le gusta trabajar solo (a)?", "scale": "E", "positive": false },
    // { "id": 16, "text": "¿se ha sentido a menudo apático (a) y cansado(a) sin razón?", "scale": "N", "positive": true },
    // { "id": 17, "text": "¿es por lo contrario animado(a) y jovial?", "scale": "E", "positive": true },
    // { "id": 18, "text": "¿se ríe a menudo de chistes groseros?", "scale": "L", "positive": false },
    // { "id": 19, "text": "¿se siente a menudo hastiado(a), harto, fastidiado?", "scale": "N", "positive": true },
    // { "id": 20, "text": "¿se siente incomodo(a) con vestidos que no son del diario?", "scale": "E", "positive": false },
    // { "id": 21, "text": "¿se distrae (vaga su mente) a menudo cuando trata de prestar atención a algo?", "scale": "N", "positive": true },
    // { "id": 22, "text": "¿puede expresar en palabras fácilmente lo que piensa?", "scale": "E", "positive": true },
    // { "id": 23, "text": "¿se abstrae (se pierde en sus pensamientos) a menudo?", "scale": "N", "positive": true },
    // { "id": 24, "text": "¿esta completamente libre de prejuicios de cualquier tipo?", "scale": "L", "positive": true },
    // { "id": 25, "text": "¿le gusta las bromas?", "scale": "E", "positive": true },
    // { "id": 26, "text": "¿piensa a menudo en su pasado?", "scale": "N", "positive": true },
    // { "id": 27, "text": "¿le gusta mucho la buena comida?", "scale": "E", "positive": true },
    // { "id": 28, "text": "cuándo se fastidia ¿necesita algún(a) amigo(a) para hablar sobre ello?", "scale": "N", "positive": true },
    // { "id": 29, "text": "¿le molesta vender cosas o pedir dinero a la gente para alguna buena causa?", "scale": "E", "positive": false },
    // { "id": 30, "text": "¿alardea (se jacta) un poco a veces?", "scale": "L", "positive": false },
    // { "id": 31, "text": "¿es usted muy susceptible (sensible) por algunas cosas?", "scale": "N", "positive": true },
    // { "id": 32, "text": "¿le gusta mas quedarse en casa, que ir a una fiesta aburrida?", "scale": "E", "positive": false },
    // { "id": 33, "text": "¿se pone a menudo tan inquieto(a) que no puede permanecer sentado(a) durante mucho rato en una silla?", "scale": "N", "positive": true },
    // { "id": 34, "text": "¿le gusta planear las cosas, con mucha anticipación?", "scale": "E", "positive": false },
    // { "id": 35, "text": "¿tiene a menudo mareos (vértigos)?", "scale": "N", "positive": true },
    // { "id": 36, "text": "¿contesta siempre una carta personal, tan pronto como puede, después de haberla leído?", "scale": "L", "positive": true },
    // { "id": 37, "text": "¿hace usted usualmente  las cosas mejor resolviéndolas solo(a) que hablando a otra persona sobre ello?", "scale": "E", "positive": false },
    // { "id": 38, "text": "¿le falta frecuentemente aire, sin haber hecho un trabajo pesado?", "scale": "N", "positive": true },
    // { "id": 39, "text": "¿es usted generalmente una persona tolerante, que no se molesta si las cosas no están perfectas?", "scale": "E", "positive": true },
    // { "id": 40, "text": "¿sufre de los nervios?", "scale": "N", "positive": true },
    // { "id": 41, "text": "¿le gustaría mas planear cosas, que hacer cosas?", "scale": "E", "positive": false },
    // { "id": 42, "text": "¿deja algunas veces para mañana. Lo que debería hacer hoy día?", "scale": "L", "positive": false },
    // { "id": 43, "text": "¿se pone nervioso(a) en lugares tales como ascensores, trenes o túneles?", "scale": "N", "positive": true },
    // { "id": 44, "text": "cuando hace nuevos amigos(as) ¿es usted usualmente quien inicia la relación o invita a que se produzca?", "scale": "E", "positive": true },
    // { "id": 45, "text": "¿sufre fuertes dolores de cabeza?", "scale": "N", "positive": true },
    // { "id": 46, "text": "¿siente generalmente que las cosas se arreglaran por si solas y que terminaran bien de algún modo?", "scale": "E", "positive": true },
    // { "id": 47, "text": "¿le cuesta trabajo  coger el sueño al acostarse en las noches?", "scale": "N", "positive": true },
    // { "id": 48, "text": "¿ha dicho alguna vez mentiras en su vida?", "scale": "L", "positive": false },
    // { "id": 49, "text": "¿dice algunas veces lo primero que se le viene a la cabeza?", "scale": "E", "positive": true },
    // { "id": 50, "text": "¿se preocupa durante un tiempo demasiado largo, después de una experiencia embarazosa?", "scale": "N", "positive": true },
    // { "id": 51, "text": "¿se mantiene usualmente hérnico(a) o encerrado (a) en si mismo(a), excepto con amigos muy íntimos?", "scale": "E", "positive": false },
    // { "id": 52, "text": "¿se crea a menudo problemas, por hacer cosas sin pensar?", "scale": "N", "positive": true },
    // { "id": 53, "text": "¿le gusta contar chistes y referir historias graciosas a sus amigos?", "scale": "E", "positive": true },
    // { "id": 54, "text": "¿se le hace más fácil ganar que perder un juego?", "scale": "L", "positive": false },
    // { "id": 55, "text": "¿se siente a menudo demasiado consciente de si mismo(a) o poco natural cuando esta con sus superiores?", "scale": "N", "positive": true },
    // { "id": 56, "text": "cuando todas las posibilidades están contra usted, ¿piensa aun usualmente que vale la pena intentar?", "scale": "E", "positive": true },
    // { "id": 57, "text": "¿siente “sensaciones” en el abdomen, antes de un hecho importante?", "scale": "N", "positive": true }
];

export default questions;
